.TH "Description" 3 "Mon May 26 2014" "Version 1.0" "PhysiCsEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Description \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Shape\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDescription\fP (const \fBEnumShapeDesc\fP i_descName, const \fBEnumShapeDescType\fP i_typeName)"
.br
.ti -1c
.RI "\fBDescription\fP & \fBoperator=\fP (const \fBDescription\fP &rvalue)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBDescription\fP &rvalue)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBDescription\fP &rvalue)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEnumShapeDesc\fP \fBmDescName\fP"
.br
.ti -1c
.RI "\fBEnumShapeDescType\fP \fBmType\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Description::Description (const \fBEnumShapeDesc\fPi_descName, const \fBEnumShapeDescType\fPi_typeName)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool Description::operator!= (const \fBDescription\fP &rvalue)\fC [inline]\fP"

.SS "\fBDescription\fP& Description::operator= (const \fBDescription\fP &rvalue)\fC [inline]\fP"

.SS "bool Description::operator== (const \fBDescription\fP &rvalue)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBEnumShapeDesc\fP Description::mDescName"

.SS "\fBEnumShapeDescType\fP Description::mType"


.SH "Author"
.PP 
Generated automatically by Doxygen for PhysiCsEngine from the source code\&.
