.TH "DrawError" 3 "Tue May 27 2014" "Version 1.0" "PhysiCsEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DrawError \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DrawError\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDrawError\fP (void)"
.br
.ti -1c
.RI "\fB~DrawError\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBStampError\fP (\fBPCE_ERROR\fP i_error)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DrawError::DrawError (void)"

.SS "DrawError::~DrawError (void)"

.SH "Member Function Documentation"
.PP 
.SS "void DrawError::StampError (\fBPCE_ERROR\fPi_error)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for PhysiCsEngine from the source code\&.
