.TH "PhysiCsEngine/EnumDefinitions.h" 3 "Tue May 27 2014" "Version 1.0" "PhysiCsEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhysiCsEngine/EnumDefinitions.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEnumShapeDesc\fP { \fBESD_NONE\fP = 0, \fBESD_BOUNDINGSPHERE\fP, \fBESD_TOTALNUMBERS\fP }"
.br
.ti -1c
.RI "enum \fBEnumShapeDescType\fP { \fBESDT_NONE\fP = 0, \fBESDT_COLLIDER\fP, \fBESDT_TOTALNUMBERS\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBEnumShapeDesc\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIESD_NONE \fP\fP
.TP
\fB\fIESD_BOUNDINGSPHERE \fP\fP
.TP
\fB\fIESD_TOTALNUMBERS \fP\fP
.SS "enum \fBEnumShapeDescType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIESDT_NONE \fP\fP
.TP
\fB\fIESDT_COLLIDER \fP\fP
.TP
\fB\fIESDT_TOTALNUMBERS \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for PhysiCsEngine from the source code\&.
