.TH "PhysiCsEngine/ErrorDefinitions.h" 3 "Tue May 27 2014" "Version 1.0" "PhysiCsEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhysiCsEngine/ErrorDefinitions.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPCE_ERROR\fP { \fBPCE_OK\fP, \fBPCE_CAPACITY\fP, \fBPCE_ADDSUBSPHERE\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPCE_ERROR\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPCE_OK \fP\fP
.TP
\fB\fIPCE_CAPACITY \fP\fP
.TP
\fB\fIPCE_ADDSUBSPHERE \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for PhysiCsEngine from the source code\&.
