.TH "PhysiCsEngine/Shape.cpp" 3 "Tue May 27 2014" "Version 1.0" "PhysiCsEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhysiCsEngine/Shape.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <typeinfo>\fP
.br
\fC#include 'DrawError\&.h'\fP
.br
\fC#include 'Shape\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for PhysiCsEngine from the source code\&.
