.TH "PhysiCsEngine/Shape.h" 3 "Tue May 27 2014" "Version 1.0" "PhysiCsEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhysiCsEngine/Shape.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&.\\PCEUtilities\\PCEUtilities\&.h'\fP
.br
\fC#include 'EnumDefinitions\&.h'\fP
.br
\fC#include 'ErrorDefinitions\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBShape\fP"
.br
.ti -1c
.RI "class \fBCollider\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PhysiCsEngine from the source code\&.
